colorScheme = "slate"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
mainSections = ["posts"]

[homepage]
  layout = "profile"
  homepageImage = ""
  showRecent = true
  showRecentItems = 5

[author]
  name = "d3vilsec"
  headline = "Marine veteran. Federal IT. Cybersecurity."
  bio = "Building, breaking, and securing things from a TV stand."
  links = [
    {github = "https://github.com/d3vilsec"},
    {twitter = "https://twitter.com/_d3vilsec"}
  ]
